# Create stellar.toml in https://domain.com/.well-known/stellar.toml

NETWORK_PASSPHRASE="Public Global RPM Network ; September 2020"
FEDERATION_SERVER="https://api.rpm.market/federation"
AUTH_SERVER="https://api.rpm.market/auth"
TRANSFER_SERVER="https://api.rpm.market"
SIGNING_KEY="GCOSDOXE5QTEDPPRRW5XI5WBY745W5EKWF64KCGD3CMPODBWUZA733T4"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
    "GA6NQUBMJARQHPNZ4YBJF3PXEX6YSRW7JOPTIWTGALVWASGSCHLRYLLZ"
]
VERSION="1.0.0"
[DOCUMENTATION]
ORG_NAME="Organization Name"
ORG_DBA="Organization DBA"
ORG_URL="https://rpm.market"
ORG_LOGO="https://rpm.market/img/logo.png"
ORG_DESCRIPTION="Team RPM"
ORG_PHYSICAL_ADDRESS="Seoul, Republic of Korea"
ORG_PHYSICAL_ADDRESS_ATTESTATION="https://www.domain.com/address_attestation.jpg"
ORG_PHONE_NUMBER="+82)02-4321-4321"
ORG_PHONE_NUMBER_ATTESTATION="https://www.domain.com/phone_attestation.jpg"
ORG_KEYBASE="Team RPM ACCOUNT"
ORG_TWITTER="orgtweet"
ORG_GITHUB="orgcode"
ORG_OFFICIAL_EMAIL="developer@rpm.market"
# asset with meta info
[[CURRENCIES]]
code="RPM"
issuer="GA6NQUBMJARQHPNZ4YBJF3PXEX6YSRW7JOPTIWTGALVWASGSCHLRYLLZ"
display_decimals=2
name="RPM"
desc="RPM"
conditions="There will only ever be 5,000,000,000 RPM tokens in existence. We will distribute the revenue share annually on Jan. 15th"
image="https://rpm.market/img/favicon.ico"
fixed_number=10000
